version: "2.1"

networks:
  elastic_net:
    external: true
    driver: bridge

services:
  mysql:
    image: mysql:8.0.14
    container_name: mysql
    networks:
      - elastic_net
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  --skip-ssl=true
    environment:
      - MYSQL_ROOT_PASSWORD=helloroot
      - MYSQL_DATABASE=facetdb
      - MYSQL_USER=hello
      - MYSQL_PASSWORD=hello
    volumes:
      - /var/lib/docker_data/mysql:/var/lib/mysql
      - /var/log/mysql:/var/log/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  elasticsearch:
    image: elasticsearch:6.6.2
    container_name: elasticsearch
    networks:
      - elastic_net
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - DISCOVERY_TYPE=single-node

  kibana:
    image: kibana:6.6.2
    container_name: kibana
#    volumes:
#      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elastic_net
    depends_on:
      - elasticsearch


#docker run -d --name elasticsearch --net somenetwork -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:tag
